/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.demo;

/**
 *
 * @author HESHAN
 */
public class ViewReports extends javax.swing.JFrame {

    /**
     * Creates new form ViewReports
     */
    public ViewReports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        ViewCustomer = new javax.swing.JButton();
        BestInCustomer = new javax.swing.JButton();
        AllCustomer = new javax.swing.JButton();
        CategorizedByQTY = new javax.swing.JButton();
        CategorizedByAmount = new javax.swing.JButton();
        OrdersByAmount = new javax.swing.JButton();
        AllOrders = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        back.setBackground(new java.awt.Color(255, 0, 0));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        ViewCustomer.setBackground(new java.awt.Color(0, 255, 51));
        ViewCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewCustomer.setForeground(new java.awt.Color(255, 255, 255));
        ViewCustomer.setText("View Customers");
        ViewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCustomerActionPerformed(evt);
            }
        });

        BestInCustomer.setBackground(new java.awt.Color(0, 255, 51));
        BestInCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BestInCustomer.setForeground(new java.awt.Color(255, 255, 255));
        BestInCustomer.setText("Best In Customer");
        BestInCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BestInCustomerActionPerformed(evt);
            }
        });

        AllCustomer.setBackground(new java.awt.Color(0, 255, 51));
        AllCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AllCustomer.setForeground(new java.awt.Color(255, 255, 255));
        AllCustomer.setText("All Customer");
        AllCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllCustomerActionPerformed(evt);
            }
        });

        CategorizedByQTY.setBackground(new java.awt.Color(0, 0, 153));
        CategorizedByQTY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CategorizedByQTY.setForeground(new java.awt.Color(255, 255, 255));
        CategorizedByQTY.setText("Categorized By  QTY");

        CategorizedByAmount.setBackground(new java.awt.Color(0, 0, 153));
        CategorizedByAmount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CategorizedByAmount.setForeground(new java.awt.Color(255, 255, 255));
        CategorizedByAmount.setText("Categorized By  Amount");

        OrdersByAmount.setBackground(new java.awt.Color(102, 102, 102));
        OrdersByAmount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OrdersByAmount.setForeground(new java.awt.Color(255, 255, 255));
        OrdersByAmount.setText("Orders By Amount");
        OrdersByAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersByAmountActionPerformed(evt);
            }
        });

        AllOrders.setBackground(new java.awt.Color(102, 102, 102));
        AllOrders.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AllOrders.setForeground(new java.awt.Color(255, 255, 255));
        AllOrders.setText("All Orders");
        AllOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ViewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CategorizedByQTY, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BestInCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AllCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(CategorizedByAmount)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(OrdersByAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AllOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(ViewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OrdersByAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CategorizedByQTY, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BestInCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(AllCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CategorizedByAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AllOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AllCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllCustomerActionPerformed
        new AllCustomerReports().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_AllCustomerActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void ViewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCustomerActionPerformed
        new ViewCustomer().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewCustomerActionPerformed

    private void BestInCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BestInCustomerActionPerformed
        new BestinCustomer().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BestInCustomerActionPerformed

    private void OrdersByAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdersByAmountActionPerformed
        new OrdersByAmount().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_OrdersByAmountActionPerformed

    private void AllOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllOrdersActionPerformed
        new AllOrders().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_AllOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllCustomer;
    private javax.swing.JButton AllOrders;
    private javax.swing.JButton BestInCustomer;
    private javax.swing.JButton CategorizedByAmount;
    private javax.swing.JButton CategorizedByQTY;
    private javax.swing.JButton OrdersByAmount;
    private javax.swing.JButton ViewCustomer;
    private javax.swing.JButton back;
    // End of variables declaration//GEN-END:variables
}
